### ISSUE TITLE
Opening and closing connections cause panic

### ISSUE THREAD

**Issue by franchoco** [niclabs/ratadns-gopher#12]
Trace:
`
net/http.(*ServeMux).ServeHTTP(0xc20803a720, 0x7ff894606308, 0xc208044b40, 0xc20815e270)
        /usr/lib/golang/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc208042840, 0x7ff894606308, 0xc208044b40, 0xc20815e270)
        /usr/lib/golang/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208044aa0)
        /usr/lib/golang/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /usr/lib/golang/src/net/http/server.go:1751 +0x35e

goroutine 49 [runnable]:
net/http.(*response).Write(0xc208044c80, 0xc2081a8130, 0x8, 0x8, 0x1, 0x1, 0xc208056b48)
        /usr/lib/golang/src/net/http/server.go:976
fmt.Fprintf(0x7ff894606a70, 0xc208044c80, 0x766b30, 0xa, 0xc208056bf8, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/fmt/print.go:189 +0xac
_/home/francisco/ratadns-gopher/src/sse.(*SSEServer).ServeHTTP(0xc20800ac50, 0x7ff894606308, 0xc208044c80, 0xc20815eb60)
        /home/francisco/ratadns-gopher/src/sse/sse.go:111 +0x680
net/http.(*ServeMux).ServeHTTP(0xc20803a720, 0x7ff894606308, 0xc208044c80, 0xc20815eb60)
        /usr/lib/golang/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc208042840, 0x7ff894606308, 0xc208044c80, 0xc20815eb60)
        /usr/lib/golang/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208044be0)
        /usr/lib/golang/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /usr/lib/golang/src/net/http/server.go:1751 +0x35e`

**Comment by capalvarez** [comment]
Solved in  92631a0
