### ISSUE TITLE
Add tests on new classes and methods

### ISSUE THREAD

**Issue by franchoco** [niclabs/ratadns-gopher#48]

**Comment by camilog** [comment]
removed old tests that used fakeredis

**Comment by camilog** [comment]
how to test gopher methods without requiring a redis connection?

**Comment by franchoco** [comment]
With fakeredis

Enviado desde mi teléfono con Cyanogen

El jul. 20, 2016 3:07 PM, "Camilo J. Gómez" <notifications@github.com> escribió:

how to test gopher methods without requiring a redis connection?

**Comment by camilog** [comment]
needs to be done a couple of TODO regarding testing equality of dictionaries inside lists
